[build]
  publish = "dist"
  command = "npm run build"

# Environment variable settings
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --production=false"

# Asset optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

# Headers for caching and security
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200